### ISSUE TITLE
What are bnd, nprod, ntprod?

### ISSUE THREAD

**Issue by Vilin97** [JuliaSmoothOptimizers/PROPACK.jl#30]
Also, what is the difference between tsvd_irl and tsvd? Thank you!

**Comment by dpo** [comment]
https://github.com/JuliaSmoothOptimizers/PROPACK.jl/blob/master/src/PROPACK.jl#L46

**Comment by dpo** [comment]
tsvd and tsvd_irl use different methods to approximate singular values and vectors; "irl" stands for "implicitly restarted Lanczos bidiagonalization". I recommend looking at the documentation section of http://sun.stanford.edu/~rmunk/PROPACK/ for full details.
